# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2.9013
    hooks:
    -   id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
        exclude: >
          (?x)^(
          todo-files/.*|
          tests/.*|
          man-roxygen/.*|
          inst/.*|
          )$
        additional_dependencies:
        - mlr-org/styler.mlr
    -   id: roxygenize
        additional_dependencies:
        -    ParamHelpers
        -    backports
        -    BBmisc
        -    checkmate
        -    data.table
        -    ggplot2
        -    methods
        -    parallelMap
        -    stats
        -    stringi
        -    survival
        -    utils
        -    XML
    -   id: use-tidy-description
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        exclude: "gunpoint.RData|yeast.RData"
        # `exclude: <regex>` to allow committing specific files.

ci:
    skip: [roxygenize]
    autoupdate_schedule: monthly
