language: r
sudo: false
cache: packages
r:
   - release
   - devel

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9
  - libgmp-dev

env:
  global:
    - secure: "WFbdUIQRi7VYUHceKrg9xnw7m+8SK658rmgWPW++zWq5J4n0ZLuTRdKHu7ijyK9zOzNGjLF+NzvnwPS+yMPJwTX/s82hrC5GAMrYs3shEvR95PwFx42nfjqU5fsKsZ9gYpqIuZoJs32yPOJ/9XBLHU8rUv5+x4Z1zM2hBJHAn74="

r_github_packages:
  - berndbischl/BBmisc
  - berndbischl/parallelMap
  - berndbischl/ParamHelpers

before_install:
  - mkdir $HOME/bin
  - ln -s $(which gcc-4.9) $HOME/bin/gcc
  - ln -s $(which g++-4.9) $HOME/bin/g++
  - export PATH=$HOME/bin:$PATH

before_script:
  - java -cp $HOME/R/Library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package thirdparty/XMeans1.0.4.zip

notifications:
  email:
    recipients:
        - michellang@gmail.com
