language: r
sudo: false
dist: trusty
cache: packages
latex: true
env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_TESTS_NLINES_=999

addons:
  apt:
    packages:
     - libgmp-dev
     - libgsl0-dev
     - libgdal-dev # for sf
     - libproj-dev # for sf
     - libgeos-dev # for sf
     - libudunits2-dev # for sf

before_install:
  - R -q -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")'
  - R -q -e 'if (!requireNamespace("genefilter", quietly = TRUE)) BiocManager::install("genefilter")'
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (!requireNamespace("curl")) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_script: R -q -e 'tic::after_script()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     all_branches: true
