language: r
sudo: false
dist: trusty
cache:
  - packages
  - ccache
env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0  # no error if suggested packs are not avail
    - _R_CHECK_TESTS_NLINES_=999
    - R_MAX_NUM_DLLS=999
    - secure: "d0xff7hriQyReF4y3/iR5sHJlXocKNKcN6/Gi/r9Hxsfuh2Hx3fouQCMSPP+Oba6MDgEvAfryToAxcmaoZByQMwgevB0OBy5xkatj3oTHmhN5Nbk3jNXxXfA6P0Oqxaf7lXVZk2+Ly+PWnbgXn0uhjzdaZo0cWtVJ660ajS0x9Q="
    - WARMUPPKGS='roxygen2 pander mlrMBO purrr mlbench mldr RWeka RWekajars knitr dplyr ggplot2 ranger randomForest kernlab Rfast igraph rjson rmarkdown shiny svglite xgboost xml2'

r_github_packages:
  - berndbischl/BBmisc
  - berndbischl/parallelMap
  - berndbischl/ParamHelpers
  - jimhester/lintr

jobs:
  fast_finish: true
  allow_failures:
    - env: TUTORIAL=HTML
    - env: TUTORIAL=PDF
  include:
    - stage: warmup-1
      env: RCMDCHECK=TRUE
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
      # only stages with the same env share a cache
      # this should be share to other stages via the cache
      before_install: R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      install:
      #  - Rscript -e 'pkgs = trimws(strsplit(Sys.getenv("WARMUPPKGS"), " ")[[1]]); pkgs = pkgs[!pkgs %in% installed.packages()]; if (length(pkgs) > 0) install.packages(pkgs)'
        - R -q -e 'tic::install()'
      script: true
    - stage: warmup-2
      env: RCMDCHECK=TRUE
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
      before_install: R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      before_script: R -q -e 'tic::before_script()'
      script: true
    - stage: check
      env: RCMDCHECK=TRUE
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
      before_install:
        - R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      warnings_are_errors: false
      before_script: R -q -e 'tic::before_script()'
      script: R -q -e 'tic::script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           branch: master
           condition:
             - $TRAVIS_PULL_REQUEST = false
             - $TRAVIS_EVENT_TYPE != cron
    - stage: Tutorial
      env:
        - TUTORIAL=HTML
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
           - imagemagick # for favicon
      latex: false
      pandoc_version: 2.1.3
      before_install: R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      install: R -q -e 'tic::install()'
      script:  R -q -e 'tic::script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           branch: master
           condition:
             - $TRAVIS_PULL_REQUEST = false
             - $TRAVIS_EVENT_TYPE != cron
    - stage: Tutorial
      env:
        - TUTORIAL=PDF
      addons:
        apt:
          packages:
           - libgmp-dev
           - libgsl0-dev
           - ghostscript # for mlr-tutorial pdf
      pandoc_version: 2.1.3
      before_install: R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'
      install: R -q -e 'tic::install()'
      script:  R -q -e 'tic::script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
         provider: script
         script: R -q -e 'tic::deploy()'
         on:
           branch: master
           condition:
             - $TRAVIS_PULL_REQUEST = false
             - $TRAVIS_EVENT_TYPE != cron

notifications:
  email:
    recipients:
      - bernd_bischl@gmx.net
      - schiffner@math.uni-duesseldorf.de
      - erich.studerus@gmail.com
  slack: mlr-org:DYNA3KIwcG9F4sQoeyTnPBhF#buildnotifications
on_success: change
on_failure: always
