language: r
env:
    global:
        - _R_CHECK_TIMINGS_=0
branches:
    only:
        - master
apt_packages:
    - r-cran-rjava
r_github_packages:
    - berndbischl/BBmisc
    - berndbischl/parallelMap
    - berndbischl/ParamHelpers
    - jimhester/covr
    - jimhester/lintr
before_script:
    - sudo R CMD javareconf
    - java -cp /usr/local/lib/R/site-library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package thirdparty/XMeans1.0.4.zip
notifications:
  email:
    recipients:
        - bernd_bischl@gmx.net
        - michellang@gmail.com
        - travis.mlr@jakob-r.de
        - larsko@cs.ubc.ca
        - schiffner@math.uni-duesseldorf.de
        - erich.studerus@gmail.com
    on_success: change
    on_failure: always
after_script:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'library(lintr);load(system.file("testdata/my_linters.rda",package="mlr",mustWork=TRUE));lint_package(linters=my_linters)'
