language: r
sudo: false
cache: packages
r:
  - release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - libgmp-dev
      - libgsl0-dev

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0  # no error if suggested packs are not avail
    - secure: "d0xff7hriQyReF4y3/iR5sHJlXocKNKcN6/Gi/r9Hxsfuh2Hx3fouQCMSPP+Oba6MDgEvAfryToAxcmaoZByQMwgevB0OBy5xkatj3oTHmhN5Nbk3jNXxXfA6P0Oqxaf7lXVZk2+Ly+PWnbgXn0uhjzdaZo0cWtVJ660ajS0x9Q="

r_check_args: "--as-cran --no-examples --no-tests"

r_packages:
  - roxygen2

r_github_packages:
  - berndbischl/BBmisc
  - berndbischl/parallelMap
  - berndbischl/ParamHelpers
  - RevolutionAnalytics/quickcheck/pkg

before_install:
  # we want to see libpaths and installed packages from cache
  - Rscript -e 'message("LIBPATHS:"); .libPaths()'
  - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,1:3]'
  # we need a very fresh version of survival for Hmisc, needs be done early in the script
  - Rscript -e 'install.packages("survival")'
  - mkdir $HOME/bin
  - ln -s $(which gcc-4.9) $HOME/bin/gcc
  - ln -s $(which g++-4.9) $HOME/bin/g++
  - ln -s $(which gfortran-4.9) $HOME/bin/gfortran
  - export PATH=$HOME/bin:$PATH
  - echo $LD_LIBRARY_PATH
  - echo $LIBRARY_PATH

script:
  - echo "DONE"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
      - bernd_bischl@gmx.net
      - larsko@cs.ubc.ca
      - schiffner@math.uni-duesseldorf.de
      - erich.studerus@gmail.com
  slack: mlr-org:DYNA3KIwcG9F4sQoeyTnPBhF#buildnotifications
on_success: change
on_failure: always

